---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala
    cache:
        enabled: true
        caches:
            default:
                maxCapacity: 50000
#        ehcache:
#            ehcacheXmlLocation: 'classpath:ehcache.xml'
#            lockTimeout: 200

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    jmx:
        unique-names: true
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
management:
    endpoints:
        enabled-by-default: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
security:
    cas:
        uriFilterPattern: "/alaAdmin/*"
        uriExclusionFilterPattern: "/images.*,/css.*,/js.*,/less.*"
        enabled: false
    oidc:
        enabled: true
        discoveryUri: https://auth-test.ala.org.au/cas/oidc/.well-known
        scope: openid profile email ala roles
        clientId: 'change me'
        secret: 'change me'
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

map:
    minLat: -41.5
    minLng: 114
    maxLat: -13.5
    maxLng: 154
    minimal:
        url: "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
        attr: "Map data &copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='https://cartodb.com/attributions'>CartoDB</a>"
        subdomains: "abcd"
